### PR TITLE
Added objectToQueryString()

### PR DESCRIPTION
**Pull request by sudogem**

### CODE REVIEW

**Comment by tuxrace** [comment]
Man, when travis  runs where is it build local or server?,  if you have time please also add a pre commit hook

**Comment by tuxrace** [comment]
@sudogem on travis where do we run npm build, local or on server?

**Comment by sudogem** [comment]
@tuxrace it will build on the server.. see sample build process.. 
travis1

**Comment by tuxrace** [comment]
What server will it build?

**Comment by sudogem** [comment]
on CF server.. try to merge this PR and check the code in travis.yml I add a variable deploy=cloudfoundry

**Pull request merged**
